### ISSUE TITLE
Time request for Smart Mode Line

### ISSUE THREAD

**Issue by ReneFroger** [Bruce-Connor/smart-mode-line#116]
Hello Bruce, 

Thanks for sharing this awesome feature to Emacs community. It's really appreciated. 

However, I would like to add something precious. 

Before I discovered Smart Mode Line, I modified my own mode line. I was very happy with my Windows-ish time display in my Emacs mode line: 

This was the code that I was using to display the time in the mode line: 

```

(defun enable-time ()
  (interactive)
  (setq display-time-24hr-format t)
  (setq display-time-day-and-date t)
  (display-time)
  ; Align the time to right
  (setq global-mode-string (remove 'display-time-string global-mode-string))
  (setq mode-line-end-spaces
    (list (propertize " " 'display '(space :align-to (- right 17)))
        'display-time-string))
 )   
(add-hook 'after-init-hook 'enable-time)  
(add-hook 'after-init-hook 'display-time-24hr-format t)  
(add-hook 'after-init-hook 'display-time-day-and-date t)  
(add-hook 'after-init-hook 'display-time)  

```

So when you apply this code without SML initialized, you will notice the time and date will be displayed on the right of your mode line. With SML, there is an empty gap on the right side of the SML. 

I tried to initialize the time after SML initialisation, but it didn't worked out. Then I changed the code of SML, without any luck. 

Any suggestion, in order to get this worked? 

Thanks in advance for your comment.

**Comment by Bruce-Connor** [comment]
Hi there. You should be able to use display-time without any modification.
In sml, the global mode string is aligned to the right of the mode-line by
default, so I think that enable-time function is unnecessary.

In other words, try activating display-time without using this enable-time
function and let me know what happens.

Hello Bruce,

Thanks for sharing this awesome feature to Emacs community. However, I'm
missing something precious.

Before I discovered Smart Mode Line, I modified my own mode line. I was
very happy with my Windows-ish time display in my Emacs mode line:

This was the code that I was using to display the time in the mode line:


(defun enable-time ()
  (interactive)
  (setq display-time-24hr-format t)
  (setq display-time-day-and-date t)
  (display-time)
  ; Align the time to right
  (setq global-mode-string (remove 'display-time-string global-mode-string))
  (setq mode-line-end-spaces
    (list (propertize " " 'display '(space :align-to (- right 17)))
        'display-time-string))
 )
(add-hook 'after-init-hook 'enable-time)
(add-hook 'after-init-hook 'display-time-24hr-format t)
(add-hook 'after-init-hook 'display-time-day-and-date t)
(add-hook 'after-init-hook 'display-time)


So when you apply this code without SML initialized, you will notice the
time and date will be displayed on the right of your mode line. With SML,
there is an empty gap on the right side of the SML.

I tried to initialize the time after SML initialisation, but it didn't
worked out. Then I changed the code of SML, without any luck.

Any suggestion, in order to get this worked?

Thanks in advance for your comment.

—
Reply to this email directly or view it on GitHub
<https://github.com/Bruce-Connor/smart-mode-line/issues/116>.

**Comment by ReneFroger** [comment]
Thanks for your comment. You're right. 

When I do the following 
```
(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'sml/apply-theme 'dark)
(add-hook 'after-init-hook 'display-time)  
```

Then I see the time in my mini buffer indeed. But I would like to enable the dates and 24-hour notation. So I modified it as following: 
 
```
(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'sml/apply-theme 'dark)
 (add-hook 'after-init-hook 'display-time-24hr-format t)  
(add-hook 'after-init-hook 'display-time-day-and-date t)  
(add-hook 'after-init-hook 'display-time)  
```
But I see only the time in 12-hour notation, without any date in the Smart Mode Line. When I disable SML, I see the correct time and date. 

Any suggestion, in order to get this working?

**Comment by Bruce-Connor** [comment]
Ok, two things:

1. It doesn't pass arguments to the function. So the following line does not apply the dark theme, it simply calls `sml/apply-theme` without arguments.

        (add-hook 'after-init-hook 'sml/apply-theme 'dark)

2. `display-time-24hr-format` and `display-time-day-and-date` are variables, so it doesn't even make sense to add them to hooks.


Instead, what you want to do is this:

    (add-hook 'after-init-hook 'sml/setup)
    (add-hook 'after-init-hook 'display-time)  
    (setq display-time-24hr-format t)
    (setq display-time-day-and-date t)

**Comment by ReneFroger** [comment]
There is a reason why I apply `add-hook`. I bounded it to the hooks, or it will ask me everytime to confirm to apply the theme. 

You're right, it makes no sense to use the `add-hook` for variables. My issue is solved now, I appreciate it. 

Thanks for that!

**Comment by Bruce-Connor** [comment]
> There is a reason why I apply `add-hook`. I bounded it to the hooks, or it will ask me everytime to confirm to apply the theme. 

`sml/setup` already calls `sml/apply-theme`, so there's no need to hook the latter. ;-)

And there's a variable I implemented for people who were having that problem. It's documented in the Readme.
