### ISSUE TITLE
automatic theme doesn't get set

### ISSUE THREAD

**Issue by manuel-uberti** [Bruce-Connor/smart-mode-line#117]
I am using latest version of ```smart-mode-line``` (```20150303.633```) on Emacs trunk (commit: ```0c4f73a```)
This how it is setup in my config:
```
(use-package smart-mode-line
  :ensure t
  :init
  (progn
    ;; Hide some modes
    (require 'rich-minority)
    (setq rm-blacklist
	  (format "^ \\(%s\\)$"
		  (mapconcat #'identity
			     '("FlyC.*"
			       "Projectile.*"
			       "PgLn"
			       "company"
			       "Undo-Tree"
			       "Wrap"
			       "hhat"
                               "SliNav"
                               "hl-s")
			     "\\|")))
    (sml/setup)
    (sml/apply-theme 'automatic)))
```
Every time I restart Emacs the theme is set to ```dark```.
It works fine if I change ```'automatic``` with any other theme. Also, ```automatic``` theme works fine if I use ```(sml/apply-theme)``` interactively.

**Comment by manuel-uberti** [comment]
To add on this: it works if I customize ```sml/theme``` and set it to ```Automatically choose between 'light, 'dark, or nil during setup. (Default and Recommended)``` (which I suppose is ```automatic```). Upon restart, now the theme is rightly set to ```automatic```.

**Comment by Bruce-Connor** [comment]
Use `(setq sml/theme 'automatic)` just before sml/setup.

The behaviour is different now because of a recent change that I'm still trying to decide whether I'll keep or not. But, in any case, your configuration unnecessarily calls apply-theme twice, so you'll probably note a speed-up at init time.

**Comment by manuel-uberti** [comment]
No luck with that. Now I have ```dark``` theme set up as soon as Emacs starts.

**Comment by Bruce-Connor** [comment]
I'm sorry, I meant to say: Use `(setq sml/theme 'automatic)` just before sml/setup and remove the `(sml/apply-theme ...)` call.

Did you do that?

**Comment by manuel-uberti** [comment]
Yes, and I removed ```'(sml/theme (quote automatic))``` in ```custom-set-variables``` too.

**Comment by Bruce-Connor** [comment]
Ok. I pushed a commit which should fix this. Let me know if it does.

**Comment by manuel-uberti** [comment]
Just grabbed from MELPA. Still no luck.

**Comment by Bruce-Connor** [comment]
That's odd. Could you let me know what's your configuration at the moment?

**Comment by manuel-uberti** [comment]
Here is the relevant code:
```
(use-package smart-mode-line
  :ensure t
  :init
  (progn
    ;; Hide some modes
    (require 'rich-minority)
    (setq rm-blacklist
	  (format "^ \\(%s\\)$"
		  (mapconcat #'identity
			     '("FlyC.*"
			       "Projectile.*"
			       "PgLn"
			       "company"
			       "Undo-Tree"
			       "Wrap"
			       "hhat"
                               "SliNav"
                               "hl-s")
			     "\\|"))
          sml/theme 'automatic)
    (sml/setup)))
```

**Comment by Bruce-Connor** [comment]
What global theme do you use? Is it activated before or after sml?

**Comment by manuel-uberti** [comment]
I'm using ```solarized-light``` ([this one](https://github.com/bbatsov/solarized-emacs), to be more precise), and it is activated before sml.

**Comment by manuel-uberti** [comment]
If it helps, I just tried activating sml before the theme but automatic still doesn't get set.

**Comment by Bruce-Connor** [comment]
Ok. What happens if you do the following:

1. Start emacs with `emacs -Q`,
2. call `M-x package-initialize`,
3. call `M-x sml/setup`

This should give you a light theme (since emacs's default theme is light). If that works, do the following:

1. Start emacs with `emacs -Q`,
2. call `M-x package-initialize`,
3. activate `solarized-light` theme,
4. call `M-x sml/setup`

And let me know if it works too.

**Comment by manuel-uberti** [comment]
First set of instructions: I have a light theme.
Second set of instructions: after calling ```M-x sml/setup```, light theme get set.

**Comment by manuel-uberti** [comment]
Actually, [solarized-theme](https://github.com/bbatsov/solarized-emacs) added support for ```smart-mode-line``` in a recent commit. Now ```light``` theme is pretty beautiful. I can stick with that if ```automatic``` is a trouble to fix.

**Comment by Bruce-Connor** [comment]
If you still feel like debugging, I can push a new version with debug information. That should tell us why automatic is giving you a dark theme.

**Comment by manuel-uberti** [comment]
Oh yes, it's the least I could do to help.

**Comment by Bruce-Connor** [comment]
Ok. The latest commit adds some debugging information. In order to turn it on, you need to do `(setq sml/-debug t)` **before** installing the new version.

If you've already installed, either reinstall it or (if you know how to do it) just recompile the installation directory.

---

Once you've done this, next time you start Emacs you will get a lot of messages in the `*Messages*` buffer describing some sml stuff. These are lines starting with _“[sml/debug]”_.
Just copy and paste here all of them (as well as anything in between).

**Comment by manuel-uberti** [comment]
Ok, this is the log:
```
[sml/debug] Entering setup
[sml/debug] custom-enabled-themes is: nil
[sml/debug] Entering -setup-theme
[sml/debug] sml/theme is: automatic
[sml/debug] (sml/global-theme-support-sml-p) is: nil
[sml/debug] (face-background (quote mode-line) nil t) is: nil
[sml/debug] (face-background (quote default) nil t) is: nil
[sml/debug] set-theme is: light
[sml/debug] set-theme is: light
[sml/debug] Entering apply-theme
[sml/debug] theme is: light
[sml/debug] sml/theme is: nil
[sml/debug] sml/-apply-theme-is-running is: nil
[sml/debug] sml/theme is: light
[sml/debug] custom-enabled-themes is: nil
[sml/debug] custom-enabled-themes is: nil
[sml/debug] sml/theme is: light
[sml/debug] theme-name is: smart-mode-line-light
```

**Comment by Bruce-Connor** [comment]
Is that during normal initialization? Is your theme dark or light in the end?

**Comment by manuel-uberti** [comment]
This happens when starting Emacs using ```emacs --daemon``` (that's what I usually do). In the end, I get the light theme.

**Comment by Bruce-Connor** [comment]
I thought the problem was that the theme was set to dark?

**Comment by manuel-uberti** [comment]
Originally, the problem was the automatic setting being ignored and dark theme being set. Now upon start automatic is still ignored, but instead of dark I get light theme.

**Comment by Bruce-Connor** [comment]
Why do you say it's being ignored? The purpose of the 'automatic setting is to decide between no theme, dark theme, or light theme based on your global theme.
Why do you say it's being ignored?

**Comment by manuel-uberti** [comment]
I got it wrong then. I supposed 'automatic set the theme to nil by default. Now is it set to light because solarized added support for smart-mode-line? If so, consider it close.

Thank you very much for the support.

**Comment by Bruce-Connor** [comment]
No. It is set to light because the default theme is light, and by the time sml is activated the `solarized` theme is not loaded yet. That's what the line `[sml/debug] custom-enabled-themes is: nil` says. There are not yet any active themes when sml is run.

If sml were loaded after the solarized theme was loaded, then 'automatic should detect that solarized has sml support and should set `sml/theme` to nil. 

The reason why this is not happening right now is probably because you start emacs without a frame. The 'automatic option is kind of shaky in that situation anyway. In that case, you can just do `(setq sml/theme nil)` before `sml/setup` is run. This will prevent sml from applying any of its themes, and that should ensure solarized gets to shine on it's own (pun intended).

**Comment by manuel-uberti** [comment]
I see, thanks for the explanation.

**Comment by Bruce-Connor** [comment]
No problem. Glad it's settled. :)
